# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 17:00
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=50, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('active', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='blogs.Category')),
            ],
        ),
    ]
