# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=20)),
                ('field2', models.DateTimeField(verbose_name='field 2')),
            ],
        ),
    ]
